ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-c"]

ARG REPO_URL=https://github.com/Ericsii/FAST_LIO_ROS2.git
ARG BRANCH=main
ARG CUDA_ARCH=87

ENV DEBIAN_FRONTEND=noninteractive

# 1. Зависимости компиляции, генераторы интерфейсов ROS2 и системные библиотеки
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev \
    pkg-config \
    ros-humble-rosidl-default-generators \
    ros-humble-rosidl-default-runtime \
    ros-humble-common-interfaces \
    ros-humble-tf2-ros \
    ros-humble-pcl-conversions \
    ros-humble-pcl-ros \
    && rm -rf /var/lib/apt/lists/*

# 2. Подготовка исходников и активация конфигурации ROS2 для Livox
WORKDIR /workspace/ros2_ws/src

RUN git clone --depth 1 https://github.com/Livox-SDK/livox_ros_driver2.git && \
    git clone -b ${BRANCH} --depth 1 ${REPO_URL} fast_lio && \
    cp /workspace/ros2_ws/src/livox_ros_driver2/package_ROS2.xml /workspace/ros2_ws/src/livox_ros_driver2/package.xml

# 3. Сборка драйвера livox_ros_driver2
WORKDIR /workspace/ros2_ws
RUN source /opt/ros/humble/setup.bash && \
    colcon build --packages-select livox_ros_driver2 \
    --cmake-args -DROS_EDITION=ROS2 -DCMAKE_BUILD_TYPE=Release \
    --parallel-workers 1

# 4. Сборка пакета FAST-LIO
RUN source /opt/ros/humble/setup.bash && \
    source /workspace/ros2_ws/install/setup.bash && \
    colcon build --packages-select fast_lio \
    --cmake-args \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCH} \
      -DCMAKE_PREFIX_PATH="/workspace/ros2_ws/install/livox_ros_driver2;/opt/ros/humble" \
    --parallel-workers 1

# 5. Настройка окружения
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "source /workspace/ros2_ws/install/setup.bash" >> /root/.bashrc

CMD ["/bin/bash"]
